version: '3'
services:
  iris:
    build: 
      context: .
    image: "iris-server:v1"
    container_name: iris
    ports:
      #- "3000:3000"
      - "8800:8800"
      - "8801:8801"
    networks:
      - chronicle
  chronicle:
    build: 
      context: "./Chronicle\ docker/"
    image: "chronicle-server:v1"
    container_name: chronicle
    restart: unless-stopped
    networks:
      - chronicle

networks:
  chronicle:
      driver: bridge