version: '3'
services:
  iris:
    image: "iris-server:v1"
    container_name: iris
    ports:
      - "3000:3000"
      - "3001:3001"
    network_mode: "host"
  chronicle:
    build: 
      context: "./Chronicle\ docker/"
    image: "chronicle-server:v1"
    container_name: chronicle
    volumes:
      - /telos/chronicle-data:/chronicle-data
    restart: unless-stopped
    network_mode: "host"